version: 2

sources:
  - name: raw
    schema: power_of_words
    tables:
      - name: raw_data

models:
  - name: stg_articles
    description: "Cleaned staging model for scraped articles"
    columns:
      - name: url
        tests:
          - not_null